import { DEFAULT_MODEL_ID, FALLBACK_MODEL_OPTIONS } from "./models";
import type { AgentId, AgentModelOption, ClaudeApiKeyField, RuntimeProviderApiFormat } from "./types";
import { CC_SWITCH_PROVIDER_PRESETS } from "./cc-switch-provider-presets.generated";

export const CODEX_DEFAULT_PRESET_ID = "codex-default";
export const CODEX_LOCAL_DEFAULT_PRESET_ID = "codex-local-default";
export const CLAUDE_LOCAL_DEFAULT_PRESET_ID = "claude-local-default";
export const HERMES_DEFAULT_PRESET_ID = "hermes-default";
export const OPENCODE_DEFAULT_PRESET_ID = "opencode-default";
export const OPENCLAW_DEFAULT_PRESET_ID = "openclaw-default";

export interface AgentProviderPreset {
  id: string;
  label: string;
  runtimeAgentId: AgentId;
  providerName?: string;
  modelProvider?: string;
  baseUrl?: string;
  wireApi?: string;
  apiFormat?: RuntimeProviderApiFormat;
  apiKeyField?: ClaudeApiKeyField;
  modelReasoningEffort?: string;
  models: AgentModelOption[];
  usesApiKey?: boolean;
  apiKeyHeaderName?: string;
  apiKeyPrefix?: string;
  extraHeaders?: Record<string, string>;
  configurableModelId?: boolean;
  configurableModelLabel?: string;
  configurableModelPlaceholder?: string;
  websiteUrl?: string;
  apiKeyUrl?: string;
  category?: string;
  environment?: Record<string, string>;
  requiresOAuth?: boolean;
  providerType?: string;
}

const LEGACY_PROVIDER_PRESETS: AgentProviderPreset[] = [
  {
    id: "codex-openai",
    label: "Codex OpenAI",
    runtimeAgentId: "codex",
    providerName: "OpenAI",
    modelProvider: "openai",
    models: FALLBACK_MODEL_OPTIONS.codex,
  },
  {
    id: "claude-code",
    label: "Claude Code",
    runtimeAgentId: "claude",
    models: FALLBACK_MODEL_OPTIONS.claude,
  },
  {
    id: "claude-code-deepseek",
    label: "DeepSeek",
    runtimeAgentId: "claude",
    providerName: "DeepSeek",
    modelProvider: "deepseek-anthropic",
    baseUrl: "https://api.deepseek.com/anthropic",
    apiFormat: "anthropic",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default (DeepSeek Flash)" },
      { id: "claude-haiku-4-5", label: "DeepSeek V4 Flash" },
      { id: "claude-opus-4-8", label: "DeepSeek V4 Pro" },
    ],
  },
  {
    id: "claude-code-glm",
    label: "GLM",
    runtimeAgentId: "claude",
    providerName: "Zhipu GLM",
    modelProvider: "glm-anthropic",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    apiFormat: "anthropic",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "glm-5.1", label: "GLM-5.1" },
    ],
  },
  {
    id: "claude-code-kimi",
    label: "Kimi",
    runtimeAgentId: "claude",
    providerName: "Kimi",
    modelProvider: "kimi-anthropic",
    baseUrl: "https://api.moonshot.cn/anthropic",
    apiFormat: "anthropic",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "kimi-k2.6", label: "Kimi K2.6" },
    ],
  },
  {
    id: "claude-code-openrouter",
    label: "OpenRouter",
    runtimeAgentId: "claude",
    providerName: "OpenRouter",
    modelProvider: "openrouter-anthropic",
    baseUrl: "https://openrouter.ai/api/v1",
    apiFormat: "openai_chat",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "anthropic/claude-sonnet-4.5", label: "Claude Sonnet" },
      { id: "anthropic/claude-opus-4.1", label: "Claude Opus" },
    ],
  },
  {
    id: "claude-code-siliconflow",
    label: "SiliconFlow",
    runtimeAgentId: "claude",
    providerName: "SiliconFlow",
    modelProvider: "siliconflow-anthropic",
    baseUrl: "https://api.siliconflow.cn/v1",
    apiFormat: "openai_chat",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "deepseek-ai/DeepSeek-V3.2", label: "DeepSeek V3.2" },
      { id: "zai-org/GLM-4.5", label: "GLM-4.5" },
    ],
  },
  {
    id: "claude-code-bailian",
    label: "Bailian",
    runtimeAgentId: "claude",
    providerName: "Alibaba Bailian",
    modelProvider: "bailian-anthropic",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiFormat: "openai_chat",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "qwen3-coder-plus", label: "Qwen3 Coder Plus" },
      { id: "qwen-max", label: "Qwen Max" },
    ],
  },
  {
    id: "claude-code-volcengine",
    label: "Volcengine",
    runtimeAgentId: "claude",
    providerName: "Volcengine",
    modelProvider: "volcengine-anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    apiFormat: "anthropic",
    usesApiKey: true,
    configurableModelId: true,
    configurableModelLabel: "Endpoint / model ID",
    configurableModelPlaceholder: "ep-m-... or doubao-seed-...",
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "doubao-seed-2-0-code-preview-latest", label: "Doubao Seed Code" },
    ],
  },
  {
    id: "claude-code-custom",
    label: "Custom",
    runtimeAgentId: "claude",
    providerName: "Custom",
    modelProvider: "custom-anthropic",
    apiFormat: "anthropic",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: CODEX_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "codex",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    runtimeAgentId: "codex",
    providerName: "DeepSeek",
    modelProvider: "deepseek",
    baseUrl: "https://api.deepseek.com",
    wireApi: "responses",
    apiFormat: "openai_chat",
    modelReasoningEffort: "high",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "deepseek-v4-flash", label: "DeepSeek V4 Flash" },
      { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
    ],
  },
  {
    id: "glm",
    label: "GLM",
    runtimeAgentId: "codex",
    providerName: "Zhipu GLM",
    modelProvider: "zhipu-glm",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    wireApi: "responses",
    apiFormat: "openai_chat",
    modelReasoningEffort: "high",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "glm-5.1", label: "GLM-5.1" },
    ],
  },
  {
    id: "kimi",
    label: "Kimi",
    runtimeAgentId: "codex",
    providerName: "Kimi",
    modelProvider: "kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    wireApi: "responses",
    apiFormat: "openai_chat",
    modelReasoningEffort: "high",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "kimi-k2.6", label: "Kimi K2.6" },
    ],
  },
  {
    id: "longcat",
    label: "LongCat",
    runtimeAgentId: "codex",
    providerName: "LongCat",
    modelProvider: "longcat",
    baseUrl: "https://api.longcat.chat/openai/v1",
    wireApi: "responses",
    apiFormat: "openai_responses",
    modelReasoningEffort: "high",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "LongCat-Flash-Chat", label: "LongCat Flash Chat" },
    ],
  },
  {
    id: "mimo",
    label: "MiMo",
    runtimeAgentId: "codex",
    providerName: "MiMo",
    modelProvider: "xiaomi-mimo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    wireApi: "responses",
    apiFormat: "openai_responses",
    modelReasoningEffort: "high",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "mimo-v2.5-pro", label: "MiMo V2.5 Pro" },
    ],
  },
  {
    id: "codex-volcengine",
    label: "Volcengine",
    runtimeAgentId: "codex",
    providerName: "Volcengine",
    modelProvider: "volcengine",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    wireApi: "responses",
    apiFormat: "openai_responses",
    modelReasoningEffort: "high",
    usesApiKey: true,
    configurableModelId: true,
    configurableModelLabel: "Endpoint / model ID",
    configurableModelPlaceholder: "ep-m-... or doubao-seed-...",
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "doubao-seed-1-6-lite-251015", label: "Doubao Seed 1.6 Lite" },
      { id: "doubao-seed-2-0-lite-260428", label: "Doubao Seed 2.0 Lite" },
      { id: "doubao-seed-1-6", label: "Doubao Seed 1.6" },
      { id: "doubao-seed-2-0-code-preview-latest", label: "Doubao Seed Code" },
    ],
  },
  {
    id: "custom",
    label: "Custom",
    runtimeAgentId: "codex",
    providerName: "Custom",
    modelProvider: "custom",
    wireApi: "responses",
    apiFormat: "openai_responses",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: "api-openai",
    label: "OpenAI API",
    runtimeAgentId: "api",
    providerName: "OpenAI",
    modelProvider: "openai-api",
    baseUrl: "https://api.openai.com/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "gpt-4o", label: "GPT-4o" },
      { id: "gpt-4o-mini", label: "GPT-4o Mini" },
    ],
  },
  {
    id: "api-anthropic",
    label: "Anthropic API",
    runtimeAgentId: "api",
    providerName: "Anthropic",
    modelProvider: "anthropic-api",
    baseUrl: "https://api.anthropic.com/v1",
    usesApiKey: true,
    apiKeyHeaderName: "x-api-key",
    apiKeyPrefix: "",
    extraHeaders: { "anthropic-version": "2023-06-01" },
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "claude-sonnet-4-6", label: "Claude Sonnet" },
      { id: "claude-opus-4-6", label: "Claude Opus" },
    ],
  },
  {
    id: "api-deepseek",
    label: "DeepSeek API",
    runtimeAgentId: "api",
    providerName: "DeepSeek",
    modelProvider: "deepseek-api",
    baseUrl: "https://api.deepseek.com/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "deepseek-v4-flash", label: "DeepSeek V4 Flash" },
      { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
    ],
  },
  {
    id: "api-glm",
    label: "GLM API",
    runtimeAgentId: "api",
    providerName: "Zhipu GLM",
    modelProvider: "glm-api",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "glm-5.1", label: "GLM-5.1" },
    ],
  },
  {
    id: "api-kimi",
    label: "Kimi API",
    runtimeAgentId: "api",
    providerName: "Kimi",
    modelProvider: "kimi-api",
    baseUrl: "https://api.moonshot.cn/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "kimi-k2.6", label: "Kimi K2.6" },
    ],
  },
  {
    id: "api-longcat",
    label: "LongCat API",
    runtimeAgentId: "api",
    providerName: "LongCat",
    modelProvider: "longcat-api",
    baseUrl: "https://api.longcat.chat/openai/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "LongCat-Flash-Chat", label: "LongCat Flash Chat" },
    ],
  },
  {
    id: "api-mimo",
    label: "MiMo API",
    runtimeAgentId: "api",
    providerName: "MiMo",
    modelProvider: "mimo-api",
    baseUrl: "https://api.xiaomimimo.com/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "mimo-v2.5-pro", label: "MiMo V2.5 Pro" },
    ],
  },
  {
    id: "api-openrouter",
    label: "OpenRouter",
    runtimeAgentId: "api",
    providerName: "OpenRouter",
    modelProvider: "openrouter-api",
    baseUrl: "https://openrouter.ai/api/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "openai/gpt-4o", label: "OpenAI GPT-4o" },
      { id: "anthropic/claude-sonnet-4.5", label: "Claude Sonnet" },
      { id: "deepseek/deepseek-chat", label: "DeepSeek Chat" },
    ],
  },
  {
    id: "api-github-models",
    label: "GitHub Models",
    runtimeAgentId: "api",
    providerName: "GitHub Models",
    modelProvider: "github-models-api",
    baseUrl: "https://models.github.ai/inference/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "openai/gpt-4o", label: "GPT-4o" },
      { id: "xai/grok-3-mini", label: "Grok 3 Mini" },
    ],
  },
  {
    id: "api-together",
    label: "Together",
    runtimeAgentId: "api",
    providerName: "Together",
    modelProvider: "together-api",
    baseUrl: "https://api.together.xyz/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "deepseek-ai/DeepSeek-V3.2", label: "DeepSeek V3.2" },
    ],
  },
  {
    id: "api-novita",
    label: "Novita",
    runtimeAgentId: "api",
    providerName: "Novita",
    modelProvider: "novita-api",
    baseUrl: "https://api.novita.ai/v3/openai",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "zai-org/glm-5.1", label: "GLM-5.1" },
      { id: "moonshotai/kimi-k2.5", label: "Kimi K2.5" },
    ],
  },
  {
    id: "api-nvidia",
    label: "NVIDIA",
    runtimeAgentId: "api",
    providerName: "NVIDIA",
    modelProvider: "nvidia-api",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "moonshotai/kimi-k2.5", label: "Kimi K2.5" },
    ],
  },
  {
    id: "api-siliconflow",
    label: "SiliconFlow",
    runtimeAgentId: "api",
    providerName: "SiliconFlow",
    modelProvider: "siliconflow-api",
    baseUrl: "https://api.siliconflow.cn/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "deepseek-ai/DeepSeek-V3.2", label: "DeepSeek V3.2" },
      { id: "zai-org/GLM-4.5", label: "GLM-4.5" },
    ],
  },
  {
    id: "api-alibaba-bailian",
    label: "Bailian",
    runtimeAgentId: "api",
    providerName: "Alibaba Bailian",
    modelProvider: "bailian-api",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "qwen3-coder-plus", label: "Qwen3 Coder Plus" },
      { id: "qwen-max", label: "Qwen Max" },
    ],
  },
  {
    id: "api-volcengine",
    label: "Volcengine",
    runtimeAgentId: "api",
    providerName: "Volcengine",
    modelProvider: "volcengine-api",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    usesApiKey: true,
    configurableModelId: true,
    configurableModelLabel: "Endpoint / model ID",
    configurableModelPlaceholder: "ep-m-... or doubao-seed-...",
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "doubao-seed-1-6-lite-251015", label: "Doubao Seed 1.6 Lite" },
      { id: "doubao-seed-2-0-lite-260428", label: "Doubao Seed 2.0 Lite" },
      { id: "doubao-seed-1-6", label: "Doubao Seed 1.6" },
    ],
  },
  {
    id: "api-tencent-hunyuan",
    label: "Hunyuan",
    runtimeAgentId: "api",
    providerName: "Tencent Hunyuan",
    modelProvider: "hunyuan-api",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "hunyuan-turbos-latest", label: "Hunyuan Turbos" },
    ],
  },
  {
    id: "api-minimax",
    label: "MiniMax",
    runtimeAgentId: "api",
    providerName: "MiniMax",
    modelProvider: "minimax-api",
    baseUrl: "https://api.minimax.chat/v1",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "MiniMax-M2", label: "MiniMax M2" },
    ],
  },
  {
    id: "api-azure-openai",
    label: "Azure OpenAI",
    runtimeAgentId: "api",
    providerName: "Azure OpenAI",
    modelProvider: "azure-openai-api",
    baseUrl: "https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT",
    usesApiKey: true,
    models: [
      { id: DEFAULT_MODEL_ID, label: "Default" },
      { id: "gpt-4o", label: "GPT-4o" },
    ],
  },
  {
    id: "api-custom",
    label: "Custom API",
    runtimeAgentId: "api",
    providerName: "Custom API",
    modelProvider: "custom-api",
    baseUrl: "https://example.com/v1",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: HERMES_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "hermes",
    models: FALLBACK_MODEL_OPTIONS.hermes,
    configurableModelId: true,
    configurableModelLabel: "Hermes model",
    configurableModelPlaceholder: "Use Hermes profile default",
  },
  {
    id: OPENCODE_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "opencode",
    usesApiKey: true,
    models: FALLBACK_MODEL_OPTIONS.opencode,
    configurableModelId: true,
    configurableModelLabel: "OpenCode model",
    configurableModelPlaceholder: "provider/model (use OpenCode default when empty)",
  },
  {
    id: OPENCLAW_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "openclaw",
    models: FALLBACK_MODEL_OPTIONS.openclaw,
    configurableModelId: true,
    configurableModelLabel: "OpenClaw one-shot model",
    configurableModelPlaceholder: "provider/model (ACP chat uses Gateway session model)",
  },
];

export const AGENT_PROVIDER_PRESETS: AgentProviderPreset[] = [
  ...CC_SWITCH_PROVIDER_PRESETS,
  {
    id: CODEX_LOCAL_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "codex",
    category: "local",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: CLAUDE_LOCAL_DEFAULT_PRESET_ID,
    label: "Default",
    runtimeAgentId: "claude",
    category: "local",
    apiFormat: "anthropic",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: "custom",
    label: "Custom",
    runtimeAgentId: "codex",
    providerName: "Custom",
    modelProvider: "custom",
    wireApi: "responses",
    apiFormat: "openai_responses",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  {
    id: "claude-code-custom",
    label: "Custom",
    runtimeAgentId: "claude",
    providerName: "Custom",
    modelProvider: "custom-anthropic",
    apiFormat: "anthropic",
    apiKeyField: "ANTHROPIC_AUTH_TOKEN",
    usesApiKey: true,
    models: [{ id: DEFAULT_MODEL_ID, label: "Default" }],
  },
  ...LEGACY_PROVIDER_PRESETS.filter(
    (preset) => preset.runtimeAgentId !== "codex" && preset.runtimeAgentId !== "claude",
  ),
];
