export const UI_TEXT = {
  zh: {
    nav: {
      chat: "对话",
      tasks: "任务",
      teams: "团队",
      workflow: "工作流",
      schedules: "定时任务",
      skills: "Skill",
      runtimes: "配置",
      agent: "Agent",
      mcp: "MCP",
    },
    chrome: {
      featureNav: "功能导航",
      search: "搜索或执行命令...",
      newChat: "新建对话",
      newAgent: "新建 Agent",
      configuredAgents: "Agent 组装",
      noConfiguredAgents: "暂无配置的 Agent",
      noChats: "新建对话后开始。",
      skillLibrary: "技能库",
      noSkills: "暂无技能",
      darkTheme: "深色主题",
      lightTheme: "浅色主题",
      toggleTheme: "切换主题",
    },
    agent: {
      title: "Agent",
      description: "组装 Agent 的名称、描述、执行配置和标签。",
      save: "保存",
      language: "界面语言",
      zh: "统一中文",
      en: "English",
      cliHelp: "选择这个 Agent 使用的命令。",
      providerHelp: "选择 Provider 预设。",
      apiKey: "API Key / Token",
      usedByAll: "同一 Provider 的 Agent 共用",
      name: "名称",
      config: "配置",
      model: "模型",
      tags: "标签",
      descriptionField: "描述",
      advancedProvider: "高级 Provider 设置",
      plugins: "Codex 插件",
      loadCatalog: "加载目录",
      manual: "手动添加",
      catalog: "目录",
      selectPlugin: "选择插件...",
      noPluginsAvailable: "暂无可用插件",
      noPluginsConfigured: "暂无插件配置",
      enabled: "启用",
      models: "模型",
      addModel: "添加模型",
      emptyAgent: "新建 Agent 后可编辑名称、描述、执行配置和标签。",
      agentDeployed: "Agent 部署成功",
    },
    workflow: {
      newWorkflow: "新建 Workflow",
      runWorkflow: "运行图",
      running: "运行中...",
      executableNodes: "可执行节点",
      noWorkDir: "未选择工作目录",
      empty: "输入任务描述开始生成工作流。",
      agentWorking: "工作流 Agent 正在处理...",
      result: "工作流图结果",
      ready: "就绪",
      invalid: "无效",
      dagValid: "DAG 有效",
      dagInvalid: "DAG 无效",
      runProgress: "运行进度",
      finalReport: "主 Agent 总结",
      completed: "工作流已完成",
      outputDocuments: "产出文档",
      files: "个文件",
      loading: "读取中",
      closePreview: "关闭文档预览",
      largeFile: "文件较大，仅显示前 512KB。",
      entryNode: "入口节点",
      terminalNode: "终止节点",
      replyToAgent: "回复工作流 Agent",
      replyToQuestion: "回复追问",
      task: "工作流任务",
      modifyPlaceholder: "让工作流 Agent 修改图或解释运行结果...",
      answerPlaceholder: "回答当前问题...",
      taskPlaceholder: "描述工作流任务...",
      send: "发送",
    },
  },
  en: {
    nav: {
      chat: "Chat",
      tasks: "Tasks",
      teams: "Teams",
      workflow: "Workflow",
      schedules: "Schedules",
      skills: "Skill",
      runtimes: "Config",
      agent: "Agent",
      mcp: "MCP",
    },
    chrome: {
      featureNav: "Feature navigation",
      search: "Search or run command...",
      newChat: "New chat",
      newAgent: "New agent",
      configuredAgents: "Agent Assembly",
      noConfiguredAgents: "No configured agents",
      noChats: "Create a chat to start.",
      skillLibrary: "Skill library",
      noSkills: "No skills",
      darkTheme: "Dark theme",
      lightTheme: "Light theme",
      toggleTheme: "Toggle theme",
    },
    agent: {
      title: "Agent",
      description: "Assemble agent profiles, execution config, and tags.",
      save: "Save",
      language: "Language",
      zh: "统一中文",
      en: "English",
      cliHelp: "Choose the command this agent runs.",
      providerHelp: "Choose a provider preset.",
      apiKey: "API Key / Token",
      usedByAll: "Used by all",
      name: "Name",
      config: "Config",
      model: "Model",
      tags: "Tags",
      descriptionField: "Description",
      advancedProvider: "Advanced provider settings",
      plugins: "Codex Plugins",
      loadCatalog: "Load catalog",
      manual: "Manual",
      catalog: "Catalog",
      selectPlugin: "Select plugin...",
      noPluginsAvailable: "No plugins available",
      noPluginsConfigured: "No plugins configured",
      enabled: "Enabled",
      models: "Models",
      addModel: "Add model",
      emptyAgent: "Create an agent to edit its profile, execution config, and tags.",
      agentDeployed: "Agent deployed",
    },
    workflow: {
      newWorkflow: "New workflow",
      runWorkflow: "Run Graph",
      running: "Running...",
      executableNodes: "executable nodes",
      noWorkDir: "No work directory selected",
      empty: "Describe a task to start generating a workflow.",
      agentWorking: "workflow agent is working...",
      result: "Workflow graph result",
      ready: "Ready",
      invalid: "Invalid",
      dagValid: "DAG valid",
      dagInvalid: "DAG invalid",
      runProgress: "Run progress",
      finalReport: "Main agent summary",
      completed: "Workflow completed",
      outputDocuments: "Output documents",
      files: "files",
      loading: "Loading",
      closePreview: "Close document preview",
      largeFile: "File is large; showing the first 512KB.",
      entryNode: "Entry node",
      terminalNode: "Terminal node",
      replyToAgent: "Reply to workflow agent",
      replyToQuestion: "Reply to grill question",
      task: "Workflow task",
      modifyPlaceholder: "Ask the workflow agent to modify the graph or explain the run...",
      answerPlaceholder: "Answer the current question...",
      taskPlaceholder: "Describe the workflow task...",
      send: "Send",
    },
  },
} as const;
