
export const WORKFLOW_TEXT = {
  zh: {
    runWorkflow: "运行工作流",
    confirmWorkflow: "确认工作流",
    confirmed: "已确认",
    awaitingConfirmation: "等待确认",
    running: "运行中...",
    executableNodes: "个可执行节点",
    noWorkDir: "未选择工作目录",
    empty: "输入任务描述，开始生成工作流。",
    agentWorking: "工作流 Agent 正在处理...",
    result: "工作流图结果",
    ready: "就绪",
    invalid: "无效",
    dagValid: "DAG 有效",
    dagInvalid: "DAG 无效",
    runProgress: "运行进度",
    pauseNode: "暂停节点",
    startNode: "启动节点",
    finalReport: "主 Agent 总结",
    completed: "工作流已完成",
    registeredArtifacts: "Agent 登记的产出",
    outputDocuments: "产出文档",
    files: "个文件",
    nodeAgentField: "Agent（当前节点）",
    nodeAgentDefault: "跟随工作流默认配置",
    nodeInfoAgent: "执行 Agent",
    nodeInfoObjective: "总目标",
    nodeInfoInputs: "输入来源",
    nodeInfoNoUpstream: "无上游节点，仅依据总目标和当前节点指令。",
    nodeInfoOutput: "产出",
    nodeInfoOutputValue: "工作完成报告与交接信息（写入共享上下文）",
    loading: "读取中",
    closePreview: "关闭文档预览",
    largeFile: "文件较大，仅显示前 512KB。",
    replyToAgent: "回复工作流 Agent",
    replyToQuestion: "回复当前追问",
    task: "工作流任务",
    modifyPlaceholder: "让工作流 Agent 修改图或解释运行结果...",
    answerPlaceholder: "回答当前问题...",
    taskPlaceholder: "描述工作流任务...",
  },
  en: {
    runWorkflow: "Run workflow",
    confirmWorkflow: "Confirm workflow",
    confirmed: "Confirmed",
    awaitingConfirmation: "Awaiting confirmation",
    running: "Running...",
    executableNodes: "executable nodes",
    noWorkDir: "No work directory selected",
    empty: "Describe a task to start generating a workflow.",
    agentWorking: "Workflow agent is working...",
    result: "Workflow graph result",
    ready: "Ready",
    invalid: "Invalid",
    dagValid: "DAG valid",
    dagInvalid: "DAG invalid",
    runProgress: "Run progress",
    pauseNode: "Pause node",
    startNode: "Start node",
    finalReport: "Main agent summary",
    completed: "Workflow completed",
    registeredArtifacts: "Agent-published artifacts",
    outputDocuments: "Output documents",
    files: "files",
    nodeAgentField: "Agent (this node)",
    nodeAgentDefault: "Follow workflow default",
    nodeInfoAgent: "Runs with",
    nodeInfoObjective: "Objective",
    nodeInfoInputs: "Inputs from",
    nodeInfoNoUpstream: "No upstream nodes; uses only the objective and this node's prompt.",
    nodeInfoOutput: "Produces",
    nodeInfoOutputValue: "Work completion report and handoff appended to shared context",
    loading: "Loading",
    closePreview: "Close document preview",
    largeFile: "File is large; showing the first 512KB.",
    replyToAgent: "Reply to workflow agent",
    replyToQuestion: "Reply to current question",
    task: "Workflow task",
    modifyPlaceholder: "Ask the workflow agent to modify the graph or explain the run...",
    answerPlaceholder: "Answer the current question...",
    taskPlaceholder: "Describe the workflow task...",
  },
} as const;
